name: VentureChat
version: '${version}'
api-version: 1.13
main: mineverse.Aust1n46.chat.MineverseChat
depend: [ Vault, PlaceholderAPI ]
softdepend: [ Towny, Factions, EssentialsDiscord ]
author: Aust1n46
website: https://bitbucket.org/Aust1n46/venturechat/
description: #1 Channels Chat plugin! Spigot + Bungee. Supports PlaceholderAPI + JSON formatting. Moderation GUI!
libraries:
  - com.zaxxer:HikariCP:${hikari}
  - com.googlecode.json-simple:json-simple:${jsonSimple}
  - commons-lang:commons-lang:${commonsLang}